#.cpd.yaml
languages:
  - typescript
  - javascript
files:
  - "src/**/*"
exclude:
  - "**/*.js"
  - "**/typings"
  - "**/tests"
  - "**/node_modules"
  - "**/app/node_modules"
  - "**/app/components"
  - "**/app/components"
reporter: json
